In [4]:
import numpy as np
print(np.ones((1, 2)))
print(np.zeros((1, 2)))
print(np.random.rand(3, 2))

[[1. 1.]]
[[0. 0.]]
[[0.82400955 0.77677261]
 [0.34202328 0.97039057]
 [0.91747388 0.13976816]]


In [8]:
np.random.rand(1, 2)

array([[[0.33506225, 0.04789221]]])